const APPAREL_CATEGORY_PRESET = [
  {
    name: 'Clothing',
    slug: 'clothing',
    sortOrder: 10,
    description: 'Core apparel catalog for tops, bottoms, and complete outfits.',
    subcategories: [
      { name: 'T-Shirts', slug: 't-shirts' },
      { name: 'Shirts', slug: 'shirts' },
      { name: 'Jeans', slug: 'jeans' },
      { name: 'Trousers', slug: 'trousers' },
      { name: 'Kurtas & Ethnic Wear', slug: 'kurtas-ethnic-wear' },
      { name: 'Dresses', slug: 'dresses' },
      { name: 'Sarees', slug: 'sarees' },
      { name: 'Jackets & Hoodies', slug: 'jackets-hoodies' },
    ],
  },
  {
    name: 'Footwear',
    slug: 'footwear',
    sortOrder: 20,
    description: 'Shoes, sandals, and daily wear footwear options.',
    subcategories: [
      { name: 'Sneakers', slug: 'sneakers' },
      { name: 'Running Shoes', slug: 'running-shoes' },
      { name: 'Formal Shoes', slug: 'formal-shoes' },
      { name: 'Sandals & Slippers', slug: 'sandals-slippers' },
      { name: 'Heels', slug: 'heels' },
      { name: 'Boots', slug: 'boots' },
    ],
  },
  {
    name: 'Activewear',
    slug: 'activewear',
    sortOrder: 30,
    description: 'Sports and gym apparel for performance and comfort.',
    subcategories: [
      { name: 'Track Pants', slug: 'track-pants' },
      { name: 'Sports T-Shirts', slug: 'sports-t-shirts' },
      { name: 'Leggings', slug: 'leggings' },
      { name: 'Sports Bras', slug: 'sports-bras' },
      { name: 'Compression Wear', slug: 'compression-wear' },
    ],
  },
  {
    name: 'Innerwear & Sleepwear',
    slug: 'innerwear-sleepwear',
    sortOrder: 40,
    description: 'Essential comfort wear for daily routines.',
    subcategories: [
      { name: 'Innerwear', slug: 'innerwear' },
      { name: 'Nightwear', slug: 'nightwear' },
      { name: 'Thermal Wear', slug: 'thermal-wear' },
      { name: 'Socks', slug: 'socks' },
    ],
  },
  {
    name: 'Accessories',
    slug: 'fashion-accessories',
    sortOrder: 50,
    description: 'Complements for apparel and footwear purchases.',
    subcategories: [
      { name: 'Belts', slug: 'belts' },
      { name: 'Caps & Hats', slug: 'caps-hats' },
      { name: 'Wallets', slug: 'wallets' },
      { name: 'Bags', slug: 'bags' },
      { name: 'Scarves & Stoles', slug: 'scarves-stoles' },
    ],
  },
  {
    name: 'Beauty & Personal Care',
    slug: 'beauty-personal-care',
    sortOrder: 60,
    description: 'Skincare, grooming, and self-care essentials.',
    subcategories: [
      { name: 'Skincare', slug: 'skincare' },
      { name: 'Hair Care', slug: 'hair-care' },
      { name: 'Fragrances', slug: 'fragrances' },
      { name: 'Makeup', slug: 'makeup' },
      { name: 'Bath & Body', slug: 'bath-body' },
    ],
  },
  {
    name: 'Home & Living',
    slug: 'home-living',
    sortOrder: 70,
    description: 'Home utility and decor products.',
    subcategories: [
      { name: 'Bedsheets & Linen', slug: 'bedsheets-linen' },
      { name: 'Kitchen Essentials', slug: 'kitchen-essentials' },
      { name: 'Decor', slug: 'home-decor' },
      { name: 'Storage & Organizers', slug: 'storage-organizers' },
      { name: 'Cleaning Supplies', slug: 'cleaning-supplies' },
    ],
  },
  {
    name: 'Electronics & Accessories',
    slug: 'electronics-accessories',
    sortOrder: 80,
    description: 'Small gadgets and electronic accessories.',
    subcategories: [
      { name: 'Mobile Accessories', slug: 'mobile-accessories' },
      { name: 'Audio', slug: 'audio' },
      { name: 'Wearables', slug: 'wearables' },
      { name: 'Computer Accessories', slug: 'computer-accessories' },
      { name: 'Power & Charging', slug: 'power-charging' },
    ],
  },
  {
    name: 'Grocery & Daily Essentials',
    slug: 'grocery-daily-essentials',
    sortOrder: 90,
    description: 'Daily needs for home and pantry.',
    subcategories: [
      { name: 'Staples', slug: 'staples' },
      { name: 'Snacks & Beverages', slug: 'snacks-beverages' },
      { name: 'Packaged Foods', slug: 'packaged-foods' },
      { name: 'Household Essentials', slug: 'household-essentials' },
      { name: 'Baby Care', slug: 'baby-care' },
    ],
  },
];

module.exports = { APPAREL_CATEGORY_PRESET };
